### PR TITLE
add fluent-plugin-rewrite-tag-filter

### PR DESCRIPTION
**Pull request by rasheedamir**
add fluent-plugin-rewrite-tag-filter

### CODE REVIEW

**Comment by rasheedamir** [comment]
@hazim1093 we still don't have Jenkinsfile for it?

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.tools.stackator.com/job/stakater%20docker/job/dockerfile-fluentd-kubernetes/job/PR-8/1/) has Failed!

**Comment by rasheedamir** [comment]
i think we need to first merge master into this branch

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker.io/stakater/fluentd-kubernetes:1.2.0-1.1.7`

**Pull request merged**
